import 'bootstrap/dist/css/bootstrap.css'
import React from 'react';



export const metadata = {
  title: "Create Next New",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
       <React.StrictMode>
            {children}
        </React.StrictMode>
        </body>
    </html>
  );
}
