import 'bootstrap/dist/css/bootstrap.css';
import React, { Suspense } from 'react';
import './globals.css';
import Head from 'next/head';

export const metadata = {
  title: "The WishList",
  description: "Generated by create next app",
  icons: {
    icon: [
      { media: '(prefers-color-scheme: light)', url: '../public/favicon.ico' }, // Light mode
      { media: '(prefers-color-scheme: dark)', url: '../public/favicon.ico' },  // Dark mode (optional)
    ],
  },
};



export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="../public/favicon.ico" type="image/png" sizes="32x32" />
      </head>
      <body >
       <React.StrictMode>
            {children}
        </React.StrictMode>
        </body>
    </html>
  );
}
