import React from 'react';
import Header from './commons/header';
import SideBar from './commons/sidebar';



export const metadata = {
  title: "Create Next New",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
       <React.StrictMode>
        <Header/>
        <SideBar/>
        <div className="body-content-wrap">
            {children}
        </div>
        </React.StrictMode>
        </body>
    </html>
  );
}
